[package]
name = "TFM_UNIR"
version = "0.0.1"
entrypoint = "unirtfm.typ"
authors = ["Victor Gonzalez Morales (UNIR)"]
license = "MIT"
description = "Plantilla para hacer un TFM de la UNIR"

[template]
path = "."
entrypoint = "tfm.typ"
thumbnail = "unir_logo.png"